### ISSUE TITLE
low quality images

### ISSUE THREAD

**Issue by petrasovaa** [dend/foggycam#10]
I am experiencing problems when downloading images, they seems to be low quality comparing to what I see online on NEST website. They don't have the NEST logo in top right corner. Basically they look like when you reload the URL with the camera, you first see this low res image without the logo and then full resolution image is shown. The download behavior is not entirely consistent, in some rare cases I get the full res image. I wonder if it has something to do with initialization, I tried to put time.sleep(15) at the beginning of the image capturing thread, but that didn't help.
I customized your code to capture always only one image and then end the script, but otherwise I didn't change anything in the initialization or capturing. Any idea what to look for?

**Comment by dend** [comment]
Thanks @petrasovaa - looking into how this can be improved.

**Comment by jrunn4** [comment]
I too just came poking around this page to post about the image quality of the images downloaded as being of lower quality than what is displayed..   Hope you figure this out!

**Comment by peterbaker** [comment]
Can confirm what @jrunn4 said. Same low quality (and essentially unusable) images, but when I open home.nest.com, the images are much sharper, and include the "Nest" logo in the upper right (which I'd like to not include either).

**Comment by petrasovaa** [comment]
See this thread for explanation:
https://nestdevelopers.io/t/how-to-improve-snapshot-quality-to-approach-or-match-video-quality/668/14

Basically, we need to pay for NEST Aware. I am closing this, since there doesn't seem to be anything we can do about it.
