### ISSUE TITLE
404 while perform_capture called

### ISSUE THREAD

**Issue by dworak** [dend/foggycam#11]
Hello, thanks for your great work!

API /get_image changed and returns 404 upon the request

INFO: sedning a request
https://nexusapi-us1.camera.home.nest.com/get_image?uuid=b11074d692b94ae1ad6281277b4d576e&width=1280&cachebuster=91dd6296c83d430d9298ab3a3052a66f
ERROR: 404

**Comment by dend** [comment]
Thanks for the feedback, @dworak - investigating.

**Comment by dend** [comment]
@dworak no repro, I confirmed that the endpoint works - make sure that you are using the correct password, and that you log in to the Nest website and accept the new Privacy Policy.
