### ISSUE TITLE
HTTPError: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by TheBrainChain** [dend/foggycam#2]
Hey! Great job on this.

I'm having an issue where I can authenticate fine and get back what appears is the proper camera UUID (confirmed with the serial # by parsing the 'initialize_user' response data). However data capture fails and I'm assuming it has something to do with the headers on the request. I've logged the traceback below.

Any help would be appreciated!
<pre>
Traceback (most recent call last):
  File "C:\Projects\NestCam\foggycam.py", line 200, in perform_capture
    response = self.merlin.open(request)
  File "C:\Python27\lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "C:\Python27\lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python27\lib\urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "C:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden
</pre>

**Comment by dend** [comment]
@TheBrainChain try pulling the latest release - I've made a couple of changes that should have fixed the header problem.

**Comment by cwwilson08** [comment]
I finally got everything working properly using docked locally. Can capture images create video and upload to cloud. 

When container is uploaded to azure I get a loop of 403. Rei itialize 403 reinitialize. Which eventually ends at http 429 error of too many requests. What could be the difference between running local and running in cloud?

**Comment by dend** [comment]
Are you deploying the container with the configuration bundled in?

@cwwilson08

**Comment by cwwilson08** [comment]
Followed your instructions to the tee. 

Another interesting fact - same image works great in google cloud.

**Comment by dend** [comment]
@cwwilson08 so weird. I am investigating this right now.

**Comment by cwwilson08** [comment]
Yes I found it odd as well. I almost gave up in frustration before I decided to try a different service. 
I can also now confirm the image works in aws as well.

I am going to try and redeploy to azure again. Although I have done this several times now. Who knows it might surprise me  :)

**Comment by dend** [comment]
@cwwilson08 regarding streaming, would be great if you can open a new issue.

Also, if you have time and desire, would be great if you could do a write-up on how you got `foggycam` working on GCP and AWS.

**Comment by kevin-og** [comment]
Same here,

  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 429: Too Many Requests

after a few capture cycles.

**Comment by dend** [comment]
I need to implement back-off logic against the service - good enhancement to add.

**Comment by dend** [comment]
Check the latest change: 8839bc9

Because the application is no longer Python-based, this is not quite applicable 🙋‍♂️
