### ISSUE TITLE
Image quality not at the best

### ISSUE THREAD

**Issue by leader80** [dend/foggycam#20]
Dear Den,

I tried your software and I like it, there is only one problem, if you want the maximum resolution you need to be logged on nest home account otherwise the snapshot is in lower quality.

Do you think is it possible to fix it?

Bests
L

**Comment by jovana** [comment]
If you check config.json, you can change the width of the images, if you have 1080HD camera you can change this this to 1920. It gives a larger image. I agree the quality is poor. But not sure if Foggy Cam can improve this. Probably something to do on the nexusapi.

**Comment by dend** [comment]
This is currently a side-effect of how the image is obtained, and that is through a snapshot API that seems to be intentionally reduced to lower resolution after a certain number of requests. Long-term, I could probably take a look at the binary stream being sent over the sockets, however that is something that will require significantly more time invested in the project.
