### ISSUE TITLE
Documentation Lacks Video Instructions

### ISSUE THREAD

**Issue by cardiac4** [dend/foggycam#21]
I was hoping to get some clarification on if this is defaulted to pull all 12 frames from nest, or if only 1 frame is pulled a second- running the script (and reading it) looks like 1 frame is pulled from the cameras every 5 seconds and then is dumped to a file, which then makes a 16 second timelapse from 200 photos. So if I wanted my videos to be 24hrs I would have to up the pull rate to around 10 pulls per second (.1) and then set my frame rate to 10, my buffer to 10*60*60*24, is this correct? I would love to use this I was just curious on this process.

Also wondering if there is support to pull from history, I have the 30 day plan and dont want to loose the data I have.

**Comment by jduke99** [comment]
Any additional clarification would be helpful here. Specifically, what configuration/code change will increase the frequency of pulls from the server?

**Comment by dend** [comment]
This is definitely an area that I need to improve. Adding it to the backlog.

**Comment by dandaman209** [comment]
Is there any way 

> Any additional clarification would be helpful here. Specifically, what configuration/code change will increase the frequency of pulls from the server?

Is there any way to increase the frequency of pulls as per jduke99?

**Comment by kposey93** [comment]
@duzkiss - right there with you bud. I'm in the same boat. Planning on getting started on this once I'm home but I anticipate running into issues due to my lack of knowledge.

@dend - thanks so much for this!

**Comment by dend** [comment]
Check the latest change: 8839bc9

This should address this issue. I will update the README with more details as the new version of the project evolves.
