### ISSUE TITLE
It no longer seems to work.

### ISSUE THREAD

**Issue by niteshgrg** [dend/foggycam#23]
I started getting this error quite some time back only but now it no longer works.

while there is no _temp folder inside src there is one inside foggycam directly but that also doesn't contain any files.
```
Applied cache buster:  1536584862000
[ Thread-10 ] INFO: Camera buffer size for  f99bd75d11eb45399bb0728ac2e8dff6 :  200
ERROR: Could not download image from URL:
https://nexusapi-us1.camera.home.nest.com/get_image?uuid=f99bd75d11eb45399bb0728ac2e8dff6&width=1280&cachebuster=1536584856000
Traceback (most recent call last):
  File "/Users/niteshgarg/foggycam/src/foggycam.py", line 350, in perform_capture
    with open(concat_file_name, 'w') as declaration_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/niteshgarg/foggycam/src/_temp/f99bd75d11eb45399bb0728ac2e8dff6.txt'

**Comment by dend** [comment]
I wonder if it has to do with the region (see #25). @niteshgrg - have you had this working before?

**Comment by abielrodriguez** [comment]
Hello @dend, I'm having the exact same issue as @niteshgrg. Let me know what kind info you might need from my setup in order to toubleshoot this.

**Comment by dend** [comment]
Check the latest change: 8839bc9

Because the application is no longer Python-based, this is not quite applicable 🙋‍♂️
