### ISSUE TITLE
Other nest_image_url setting for Europe users (Europe users)

### ISSUE THREAD

**Issue by jovana** [dend/foggycam#25]
I hade some issues get this script working, I got retive a 404 error. I found out because I'am located in Europe I had to change the URL:

```
    # URL Settings for US
    # nest_image_url = 'https://nexusapi-us1.camera.home.nest.com/get_image?uuid=#CAMERAID#&width=#WIDTH#&cachebuster=#CBUSTER#'
    
    # URL Settings for EUROPE
    nest_image_url = 'https://nexusapi-eu1.camera.home.nest.com/get_image?uuid=#CAMERAID#&width=#WIDTH#&cachebuster=#CBUSTER#'
```

**Comment by dend** [comment]
That's a good catch. I wonder if there are other areas that we need to cover, such as Asia, Africa and Australia?

I will create a task to implement a switch for this.

**Comment by clinthend** [comment]
Starting today I am getting 403 forbidden errors when using the nest image url
https://nexusapi-us1.dropcam.com/get_image?uuid=0f0ed231e7394be3802d8023621518e6&width=560

Does anyone know if links are changing ---- the page source of the live public cam feed still lists this is the og:image link.

There is a 
https://nexusapi-us1.camera.home.nest.com/get_image?uuid=0f0ed231e7394be3802d8023621518e6&width=560  link that works ---- but only when logged in to home.nest.com     on the same browser.  

I can't find a way to pass along the login credentials in the URL.

I was using wget to download the image every 3 minutes.

**Comment by dend** [comment]
Check the latest change: 8839bc9

I've made some pretty big changes to the application infrastructure, so this should be addressed.
