### ISSUE TITLE
ImportError: No module named request

### ISSUE THREAD

**Issue by dandaman209** [dend/foggycam#29]
I am not that tech savvy. But I believe I got everything setup properly. Nonetheless, I seem to be getting an error when attempting to run start.py. Any help is greatly appreciated.

C:\Users\donny\Desktop\foggycam-master\src>python start.py
Traceback (most recent call last):
  File "start.py", line 6, in <module>
    from foggycam import FoggyCam
  File "C:\Users\donny\Desktop\foggycam-master\src\foggycam.py", line 3, in <module>
    from urllib.request import urlopen
ImportError: No module named request

C:\Users\donny\Desktop\foggycam-master\src>

**Comment by jay-star** [comment]
Did you try `python3 start.py`?

**Comment by dandaman209** [comment]
It worked. Ty!



On December 18, 2018 at 10:19:09 AM, jay-star (notifications@github.com) wrote:

Did you try python3 start.py?

**Comment by dend** [comment]
Check the latest change: 8839bc9

Because the application is no longer Python-based, this is not quite applicable 🙋‍♂️
