### ISSUE TITLE
Images created by script are DRM? - Rainbow pattern

### ISSUE THREAD

**Issue by cwwilson08** [dend/foggycam#3]
Hi first off I am very impressed with this. Issue I am having is that all my capture images are coming through with a rainbow of colors instead of a clear image of my NEST cam. If I use a browser I get a clean image.

![image](https://user-images.githubusercontent.com/33009556/35112451-ee5ef374-fc32-11e7-8eb9-76da8c786cfa.png)

**Comment by cwwilson08** [comment]
I do  not see anything released newer than what I had tried.

**Comment by dend** [comment]
@cwwilson08 try this: https://github.com/dend/foggycam/releases/tag/1.1

If this doesn't work, I will try to replicate the issue again. Do you see one or multiple cameras? I suspect you are running this project on Windows?

**Comment by cwwilson08** [comment]
Hi, You are correct I am running on windows and I am not using docker and azure. I had to modify the code a bit to make it work (was choking on finding ffmpeg, also removed the call for the azure cloud integration as that was well beyond me for the moment). I don't know if what I did could cause the visual issues. Everything seemed to hum along ok including making completely green videos. 

Using the new code with the same modifications I used on previous versions I now get this.
![image](https://user-images.githubusercontent.com/33009556/35362328-d2d5faa8-0119-11e8-8e6b-676f96b1abe4.png)

I am now at point where I am clueless as to what to try to make this work.
I am really a completely new to anything code related so I was actually surprised I got as far as I did.

**Comment by dend** [comment]
@cwwilson08 I just updated the source with Python 3 support, and tested that it works properly on Windows. Can you try running the latest code and see if the issue still repro-s for you? I can't seem to catch the issue with rainbow-pattern images.

**Comment by cwwilson08** [comment]
Yes the images now capture cleanly.

It will not produce a video due to failure of finding the ffmpeg file. Something to do with the check if it is present or not I think.

**Comment by dend** [comment]
@cwwilson08 try the code from the `analog_artifact` branch: https://github.com/dend/foggycam/tree/analog_artifact

**Comment by dend** [comment]
Closing this as the latest version should resolve this issue.
