### ISSUE TITLE
Record when motion detected...

### ISSUE THREAD

**Issue by dandaman209** [dend/foggycam#30]
It would be great to have the option to record only when motion is detected. In addition to this, maybe even the option to record only when there is a detection of motion for longer periods of time.

**Comment by jay-star** [comment]
This is almost certainly infeasible considering we are only taking image snapshots, with multiple seconds in between each grab, then combining those into videos. We don't actually have a video stream. Personally, I like that kind of motion detection as well... so I am using foggycam to supplement my single subscription: unlimited days stored on NAS w/ foggycam = $0/yr, plus 5 days of Nest recordings and motion alerts = $50/yr 

I disagree heavily with the stacking cost of multiple Nest subscriptions, the price increase for 10/30 days, etc. But $50/yr for some killer features is worth it to me, personally. You might consider the same approach.

**Comment by dandaman209** [comment]
I'm with you.

**Comment by NateRobinsonS** [comment]
I notice that the previous detection event, including a "start" and "stop" timestamp, is included in the camera data (as dumped to stdout when foggycam first starts).  Real-time detection is almost certainly infeasible for foggycam, but would it make sense to poll the event data regularly and, when a detection event occurred, request the (now slightly old) images between the two timestamps?

**Comment by dend** [comment]
This is a great suggestion, but as others mentioned, the tool does not do real-time stream processing, and as such, I currently have no plans on tracking motion. You could potentially take the code and implement some logic that does check images against a given baseline to detect significant changes (e.g. large object coming into view), but that's out of scope for this project.
