### ISSUE TITLE
need help with installation

### ISSUE THREAD

**Issue by BramWerbrouck** [dend/foggycam#31]
I doesn't seem to work on my MAC either on my rPI.. can anyone tell me step-by-step how to install this, I'm a newbie but I am very interested in the foggy cam

**Comment by dend** [comment]
@BramWerbrouck the `README` covers the installation process - are you running into specific issues?

**Comment by kratos13** [comment]
I suggest you build using #virtualenv. If you are building with v1.3, PLEASE ensure you are building your #virtualenv with pip3 (Python3). 

@dend , I LOVE what you've done with this project. 

 For everyone else, here are a few notes that got me going :: 

1) Install using #virtualenv
# virtualenv -p /usr/bin/python3 foggyCam

2) # cd foggyCam/

3) # source bin/activate

4) # git clone https://github.com/dend/foggycam.git

5) # unzip 1.3.zip

6) # cd foggycam-1.3

7) # sudo pip3 install -r requirements.txt

8) # pip3 install cryptography

9) ((** in foggycam.py **))
Replace :: response.read()
with :: response.read().decode('utf-8')
!!! EXCEPT! for line 288 !!!

10) Then, run and enjoy :: 
# python3 src/start.py 

((Works with multiple Nest-Cams; just stores them by their UUID)).

**Comment by dend** [comment]
Thanks for the notes, @kratos13. I've since moved the project to C# from Python, so instructions are somewhat different, but should still be covered in the README. Appreciate the interest in the project!
