### ISSUE TITLE
a couple of things

### ISSUE THREAD

**Issue by foo8ar** [dend/foggycam#38]
Thx for the software!

One major and a couple of minor things.
I've got three cams. They all seems to be identified
INFO: Camera UUID:dd5eXXXXXXXX338baea8041949b441e
INFO: Camera UUID:a256XXXXXXXX420ca3f6429e833ab2b5
INFO: Camera UUID:de92XXXXXXXX45a8b91cf8fec61609c5
However only two of them seems to be polled with data and filling the image directory and subsequently the video directory. 
Can I help to debug in any way?

The minor ones are that the azure code shouldn't be executed if not configured. I don't use azure. Yes I could uncomment the relevant stuff, which I did.

And then it would be really nice if it was possible to get longer consolidated videos 

thx
/t

**Comment by dend** [comment]
Check the latest change: 8839bc9

This should address the core issue. Multi-camera support should come shortly.
