### ISSUE TITLE
Various windows issues

### ISSUE THREAD

**Issue by AlexHimself** [dend/foggycam#4]
I'm weak on Python, but I think there are some windows issues. I'm using Python 3.6.4 w/Windows 10 and after populating the config and running `python start.py`, I get tons of errors regarding missing parenthesis around all of the `print` statements.

So I edited all of the code to be `print (whatever)` and now I'm getting errors with `urllib2` missing.

**Comment by dend** [comment]
Can you try building this with Python 2.7x?
https://www.python.org/ftp/python/2.7.14/python-2.7.14.msi

**Comment by dend** [comment]
@AlexHimself try pulling the latest version - I've just added Python 3.6 support. This should solve the issue. If not, comment again and I will be happy to address this.
