### ISSUE TITLE
Audio Not Supported

### ISSUE THREAD

**Issue by davidrenne** [dend/foggycam#43]
Before installing, I was wondering if the video files at all have audio embedded.  I read in your readme that audio is not supported, so do the videos just come with video only and no audio?

Or do you mean that audio only streams are not supported.

I dont want to install this if audio is not embedded in the mpg streams.

Ill close the issue once you get a chance to respond to my question.

Thank you!

**Comment by kweitzner** [comment]
There is no audio. It grabs the images, stores them until it hits a threshold that's set, and then stitches them together as a video.

**Comment by davidrenne** [comment]
Aww damn.  Good research and hacking with python regardless!  Onto paying 100 dollars a year most likely for myself.  Im taking a break off it for now and seeing what things I really miss on my camera as far as clips.
