### ISSUE TITLE
Video creation stalls image downloading - ffmpeg needs to be moved to seperate thread

### ISSUE THREAD

**Issue by TokugawaHeavyIndustries** [dend/foggycam#45]
When the ffmpeg process runs to concatenate the images to a video, the program pauses until processing is complete, then clears images and starts over.

Video processing needs to be moved to a seperate thread.  I'm thinking move images to a working folder, start re-downloading new images, and have ffmpeg process the images in the working folder.  When done, delete images in working folder, and wait for a new batch of 200 (or whatever the buffer is) to copy into the working folder.

**Comment by dend** [comment]
Check the latest change: 8839bc9

This should address this issue.
