### ISSUE TITLE
Can't access with migrated account

### ISSUE THREAD

**Issue by Angrod** [dend/foggycam#46]
is there a way to sign in as a migrated account? getting the 401 unauthorized error, only way for me to log into nest is through the "sign in using google" option. Username/password doesn't work for me.

**Comment by dend** [comment]
I haven't had a chance to look at this yet, but I would imagine that there needs to be some custom implementation of the auth logic with the Google account, that the current logic is simply not built to support. I will try to take a look at this in my free time. If anyone is willing to drop in some implementation information, I am happy to have it integrated!

**Comment by gitthismoney** [comment]
dang i am getting this too but my account is not even migrated yet... 

Also want to give a big THANK YOU for the years we successfully used your software - we used it to make time lapse videos of many events we hosted at our space. Thank you! 

user@users-mac src % python3 start.py
Welcome to FoggyCam 1.0 - Nest video/image capture tool
/Users/user/Desktop/foggycam/config.json
Unpickling cookies...
Failed to re-use the cookies. Re-initializing session...
INFO: Initializing session...
INFO: Session initialization complete!
INFO: Performing user login...
INFO: Auth post data
access_token=
b'{"status": 400, "items": [], "status_description": "bad-request", "status_detail": "Invalid Request"}'
INFO: Initializing current user...
INFO: Requesting user data from:
https://home.nest.com/api/0.1/user//app_launch
Traceback (most recent call last):
  File "start.py", line 16, in <module>
    CAM.start()
  File "/Users/user/Desktop/foggycam/src/foggycam.py", line 78, in start
    self.initialize_user()
  File "/Users/user/Desktop/foggycam/src/foggycam.py", line 248, in initialize_user
    response = self.merlin.open(request)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 649, in http_error_default  
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

**Comment by doctorkb** [comment]
I’ve seen this resolved by the folks who work on the unofficial Nest php API.

https://github.com/gboudreau/nest-api

**Comment by guyank** [comment]
I'm seeing the same problem.  Has anyone managed to solve this?

**Comment by touche112** [comment]
I'm open to starting a bounty for solving this issue.

**Comment by nextshell** [comment]
So, there's a way to [obtain the right cookies](https://github.com/chrisjshull/homebridge-nest#using-a-google-account), and modify the code to use the new authentication.

I'll try looking at it, but I can't make any promises!

**Comment by nextshell** [comment]
@touche112[ here's](https://github.com/nextshell/foggycam2) a working version.

I've changed it too much to be able to merge it back into this repo.

**Comment by touche112** [comment]
@nextshell Awesome!

**Comment by dend** [comment]
Check the latest change: 8839bc9

This should address this issue.
