### ISSUE TITLE
It seems that Nest has changed their login api

### ISSUE THREAD

**Issue by sychen52** [dend/foggycam#47]
Can anyone figure out the new way of login?

**Comment by daytonajrw** [comment]
I agree.  I was good until I restarted by NAS for an update and can no longer connect as well.  Getting 400 and 404 errors.

This is my error log...

root@freenas:~ # jexec 2 python3.6 /usr/src/start.py
Welcome to FoggyCam 1.0 - Nest video/image capture tool
/usr/config.json
Unpickling cookies...
Intializing 2FA session...
https://home.nest.com/session?=REMOVED
HTTP Error 400: Bad Request
INFO: Performing user login...
INFO: Auth post data
access_token=REMOVED
b'{"status": 403, "items": [], "status_description": "unauthorized", "status_detail": "Unauthorized."}'
INFO: Initializing current user...
INFO: Requesting user data from:
https://home.nest.com/api/0.1/user//app_launch
Traceback (most recent call last):
  File "/usr/src/start.py", line 16, in <module>
    CAM.start()
  File "/usr/src/foggycam.py", line 78, in start
    self.initialize_user()
  File "/usr/src/foggycam.py", line 248, in initialize_user
    response = self.merlin.open(request)
  File "/usr/local/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by sychen52** [comment]
> 
> 
> I agree. I was good until I restarted by NAS for an update and can no longer connect as well. Getting 400 and 404 errors.
> 
> This is my error log...
> 
> root@freenas:~ # jexec 2 python3.6 /usr/src/start.py
> Welcome to FoggyCam 1.0 - Nest video/image capture tool
> /usr/config.json
> Unpickling cookies...
> Intializing 2FA session...
> https://home.nest.com/session?=REMOVED
> HTTP Error 400: Bad Request
> INFO: Performing user login...
> INFO: Auth post data
> access_token=REMOVED
> b'{"status": 403, "items": [], "status_description": "unauthorized", "status_detail": "Unauthorized."}'
> INFO: Initializing current user...
> INFO: Requesting user data from:
> https://home.nest.com/api/0.1/user//app_launch
> Traceback (most recent call last):
> File "/usr/src/start.py", line 16, in
> CAM.start()
> File "/usr/src/foggycam.py", line 78, in start
> self.initialize_user()
> File "/usr/src/foggycam.py", line 248, in initialize_user
> response = self.merlin.open(request)
> File "/usr/local/lib/python3.6/urllib/request.py", line 532, in open
> response = meth(req, response)
> File "/usr/local/lib/python3.6/urllib/request.py", line 642, in http_response
> 'http', request, response, code, msg, hdrs)
> File "/usr/local/lib/python3.6/urllib/request.py", line 570, in error
> return self._call_chain(*args)
> File "/usr/local/lib/python3.6/urllib/request.py", line 504, in _call_chain
> result = func(*args)
> File "/usr/local/lib/python3.6/urllib/request.py", line 650, in http_error_default
> raise HTTPError(req.full_url, code, msg, hdrs, fp)
> urllib.error.HTTPError: HTTP Error 404: Not Found

If you are interested, you can give this repo a try. https://github.com/sychen52/nest-camera-site

**Comment by pjockey** [comment]
I seem to be having a similar issue to this. I'm Running MX19 (Debian 10/Buster) and the 5.4.0 kernel. The errors are listed below:

```
INFO: Requesting user data from:
https://home.nest.com/api/0.1/user//app_launch
Traceback (most recent call last):
  File "start.py", line 15, in <module>
    CAM = FoggyCam(username=CONFIG.username, password=CONFIG.password)
  File "/home/scott/Downloads/foggycam/src/foggycam.py", line 76, in __init__
    self.initialize_user()
  File "/home/scott/Downloads/foggycam/src/foggycam.py", line 246, in initialize_user
    response = self.merlin.open(request)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized
```
Is there a reason for the  missing info in this line"
`https://home.nest.com/api/0.1/user//app_launch`

**Comment by sychen52** [comment]
Just FYI, I implement another version using google log in.
https://github.com/sychen52/nest-camera-site

**Comment by jasonsf** [comment]
Has anyone attempted to port @sychen52 's login method to the python code?

**Comment by rarrr** [comment]
I've done some janky python to get it to work but you'll need to get the cookie values yourself and it seems they've limited it to 2.5 frames a second. Not the best.

**Comment by dend** [comment]
See latest change: 8839bc967cea23cd253c5c3a685da3ed149ca6f6

This should address the changes related to authentication.
