### ISSUE TITLE
Python errors

### ISSUE THREAD

**Issue by kevin-og** [dend/foggycam#5]
Running script on Ubuntu 16.04.

Traceback (most recent call last):
  File "start.py", line 6, in <module>
    from foggycam import FoggyCam
  File "/home/kevin/foggycam/src/foggycam.py", line 15, in <module>
    from azurestorageprovider import AzureStorageProvider
  File "/home/kevin/foggycam/src/azurestorageprovider.py", line 3, in <module>
    from azure.storage.blob import BlockBlobService, ContentSettings
ImportError: No module named azure.storage.blob

commented out from azurestorageprovider import AzureStorageProvider in foggycam.py to troubleshoot, get further but now getting host of other errors (HTTP Error 401: Unauthorized)

upload_to_azure in config.json is on false.

**Comment by kevin-og** [comment]
Woop I believe the problems I found are related to 2FA enabled on my account.

**Comment by dend** [comment]
@kevin-og should not be 2FA. Try `pip install -r requirements.txt` in the project folder.

**Comment by kevin-og** [comment]
You're right, system was lacking dependencies, unrelated to 2FA (though 2FA is unsupported).

**Comment by dend** [comment]
Closing this issue as it was a dependency problem.
