### ISSUE TITLE
Old Authentication Still Possible?

### ISSUE THREAD

**Issue by daltonch** [dend/foggycam#53]
I have refused to convert my account to Google since it breaks some of my other integrations so is it still possible to authenticate directly with Nest username/password? I'd like to give this a try but account conversion is a one way street.

Thanks

**Comment by dend** [comment]
Thanks for the feedback! Unfortunately, the current approach that I am covering here is only using the Google authentication. I would be happy to explore the approach to maintain legacy auth in the future (and if there is free time 😄), but currently do not have an old-school account, and given that it's on the way out (not sure how long it will still be supported), I don't currently plan to add support for it.

The history of the project is still available if you are interested in [seeing how I've implemented the legacy auth](https://github.com/dend/foggycam/tree/38d4f45d8dfc0653e5548e3b1d85eb1021ad118d) for the first release of `foggycam`.
