### ISSUE TITLE
Decoding failed, ffmpeg log attatched

### ISSUE THREAD

**Issue by rarrr** [dend/foggycam#55]
a 1kb mp4 file is created, I enabled debug at this is ffmpeg's output.

> ffmpeg version 4.3.1-2021-01-01-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
>   built with gcc 10.2.0 (Rev5, Built by MSYS2 project)
>   configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
>   libavutil      56. 51.100 / 56. 51.100
>   libavcodec     58. 91.100 / 58. 91.100
>   libavformat    58. 45.100 / 58. 45.100
>   libavdevice    58. 10.100 / 58. 10.100
>   libavfilter     7. 85.100 /  7. 85.100
>   libswscale      5.  7.100 /  5.  7.100
>   libswresample   3.  7.100 /  3.  7.100
>   libpostproc    55.  7.100 / 55.  7.100
> [h264 @ 000001b1bc79fc80] non-existing PPS 0 referenced
>     Last message repeated 1 times
> [h264 @ 000001b1bc79fc80] decode_slice_header error
> [h264 @ 000001b1bc79fc80] no frame!
> [h264 @ 000001b1bc79fc80] non-existing PPS 0 referenced
>     Last message repeated 1 times
> [h264 @ 000001b1bc79fc80] decode_slice_header error
> [h264 @ 000001b1bc79fc80] no frame!
> [h264 @ 000001b1bc79fc80] non-existing PPS 0 referenced
>     Last message repeated 1 times
> [h264 @ 000001b1bc79fc80] decode_slice_header error
> [h264 @ 000001b1bc79fc80] no frame!
> [h264 @ 000001b1bc79fc80] non-existing PPS 0 referenced
>     Last message repeated 1 times
> [h264 @ 000001b1bc79fc80] decode_slice_header error
> [h264 @ 000001b1bc79fc80] no frame!
> [h264 @ 000001b1bc79fc80] non-existing PPS 0 referenced
>     Last message repeated 1 times
> [h264 @ 000001b1bc79fc80] decode_slice_header error
> [h264 @ 000001b1bc79fc80] no frame!
> [h264 @ 000001b1bc79fc80] non-existing PPS 0 referenced
>     Last message repeated 1 times
> [h264 @ 000001b1bc79fc80] decode_slice_header error
> [h264 @ 000001b1bc79fc80] no frame!
> [h264 @ 000001b1bc79fc80] non-existing PPS 0 referenced
>     Last message repeated 1 times
> [h264 @ 000001b1bc79fc80] decode_slice_header error
> [h264 @ 000001b1bc79fc80] no frame!
> [h264 @ 000001b1bc79fc80] non-existing PPS 0 referenced
>     Last message repeated 1 times
> [h264 @ 000001b1bc79fc80] decode_slice_header error
> [h264 @ 000001b1bc79fc80] no frame!
> [h264 @ 000001b1bc79fc80] non-existing PPS 0 referenced
>     Last message repeated 1 times
> [h264 @ 000001b1bc79fc80] decode_slice_header error
> [h264 @ 000001b1bc79fc80] no frame!
> [h264 @ 000001b1bc79fc80] non-existing PPS 0 referenced
>     Last message repeated 1 times
> [h264 @ 000001b1bc79fc80] decode_slice_header error
> [h264 @ 000001b1bc79fc80] no frame!
> [h264 @ 000001b1bc79fc80] non-existing PPS 0 referenced
>     Last message repeated 1 times
> [h264 @ 000001b1bc79fc80] decode_slice_header error
> [h264 @ 000001b1bc79fc80] no frame!
> [h264 @ 000001b1bc79fc80] non-existing PPS 0 referenced
>     Last message repeated 1 times
> [h264 @ 000001b1bc79fc80] decode_slice_header error
> [h264 @ 000001b1bc79fc80] no frame!
> [h264 @ 000001b1bc79fc80] Reinit context to 1280x720, pix_fmt: yuvj420p
> [h264 @ 000001b1bc79fc80] co located POCs unavailable
>     Last message repeated 5 times
> [h264 @ 000001b1bc79e2c0] max_analyze_duration 5000000 reached at 5013333 microseconds st:0
> [h264 @ 000001b1bc79e2c0] decoding for stream 0 failed
> Input #0, h264, from 'pipe:':
>   Duration: N/A, bitrate: N/A
>     Stream #0:0: Video: h264 (Main), 1 reference frame, yuvj420p(pc, bt709, progressive, left), 1280x720 [SAR 1:1 DAR 16:9], 15.58 fps, 15 tbr, 1200k tbn, 30 tbc
> Stream mapping:
>   Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
> [h264 @ 000001b1bd3f54c0] Reinit context to 1280x720, pix_fmt: yuvj420p
> [h264 @ 000001b1bc8273c0] co located POCs unavailable
> [h264 @ 000001b1bc827840] co located POCs unavailable
> [h264 @ 000001b1bc827d00] co located POCs unavailable
> [h264 @ 000001b1bd3f54c0] co located POCs unavailable
> [h264 @ 000001b1bd545080] co located POCs unavailable
> [h264 @ 000001b1bc82aa80] co located POCs unavailable
> [h264 @ 000001b1bc828a80] co located POCs unavailable
> [h264 @ 000001b1bc829840] co located POCs unavailable
> [h264 @ 000001b1bcd9b380] co located POCs unavailable
> [h264 @ 000001b1bc810ec0] co located POCs unavailable
> [h264 @ 000001b1bc813500] co located POCs unavailable
> [h264 @ 000001b1bd526480] co located POCs unavailable
> [h264 @ 000001b1bc827840] co located POCs unavailable
> [h264 @ 000001b1bc82a180] co located POCs unavailable
> [h264 @ 000001b1bd3f54c0] co located POCs unavailable
> [h264 @ 000001b1bc7a3200] co located POCs unavailable
> [h264 @ 000001b1bc82aa80] co located POCs unavailable
> [h264 @ 000001b1bc82a600] co located POCs unavailable
> [h264 @ 000001b1bc829840] co located POCs unavailable
> [h264 @ 000001b1bc8273c0] co located POCs unavailable
> [h264 @ 000001b1bc810ec0] co located POCs unavailable
> [h264 @ 000001b1bc812bc0] co located POCs unavailable
> [h264 @ 000001b1bd526480] co located POCs unavailable
> [h264 @ 000001b1bd545080] co located POCs unavailable
> [h264 @ 000001b1bc82a180] co located POCs unavailable
> [h264 @ 000001b1bc827d00] co located POCs unavailable
> [h264 @ 000001b1bc7a3200] co located POCs unavailable
> [h264 @ 000001b1bcd9b380] co located POCs unavailable
> [h264 @ 000001b1bc82a600] co located POCs unavailable
> [h264 @ 000001b1bc828a80] co located POCs unavailable
> [h264 @ 000001b1bc8273c0] co located POCs unavailable
> [h264 @ 000001b1bc827840] co located POCs unavailable
> [h264 @ 000001b1bc812bc0] co located POCs unavailable
> [h264 @ 000001b1bc813500] co located POCs unavailable
> [h264 @ 000001b1bd545080] co located POCs unavailable
> [h264 @ 000001b1bc82aa80] co located POCs unavailable
> [h264 @ 000001b1bc827d00] co located POCs unavailable
> [h264 @ 000001b1bd3f54c0] co located POCs unavailable
> [h264 @ 000001b1bcd9b380] co located POCs unavailable
> [h264 @ 000001b1bc810ec0] co located POCs unavailable
> [h264 @ 000001b1bc828a80] co located POCs unavailable
> [h264 @ 000001b1bc829840] co located POCs unavailable
> [h264 @ 000001b1bc827840] co located POCs unavailable
> [h264 @ 000001b1bc82a180] co located POCs unavailable
> [h264 @ 000001b1bc813500] co located POCs unavailable
> [h264 @ 000001b1bd526480] co located POCs unavailable
> [h264 @ 000001b1bc82aa80] co located POCs unavailable
> [h264 @ 000001b1bc82a600] co located POCs unavailable
> [h264 @ 000001b1bd3f54c0] co located POCs unavailable
> [h264 @ 000001b1bc7a3200] co located POCs unavailable
> [h264 @ 000001b1bc810ec0] co located POCs unavailable
> [h264 @ 000001b1bc812bc0] co located POCs unavailable
> [h264 @ 000001b1bc829840] co located POCs unavailable
> [h264 @ 000001b1bc8273c0] co located POCs unavailable
> [h264 @ 000001b1bc82a180] co located POCs unavailable
> [h264 @ 000001b1bc827d00] co located POCs unavailable
> [h264 @ 000001b1bd526480] co located POCs unavailable
> [h264 @ 000001b1bd545080] co located POCs unavailable
> [h264 @ 000001b1bc82a600] co located POCs unavailable
> [h264 @ 000001b1bc828a80] co located POCs unavailable
> [h264 @ 000001b1bc7a3200] co located POCs unavailable
> [h264 @ 000001b1bcd9b380] co located POCs unavailable
> [h264 @ 000001b1bc812bc0] co located POCs unavailable
> [h264 @ 000001b1bc813500] co located POCs unavailable
> [log] Writing of 2021-08-1--16-07-40.mp4 completed.
> [h264 @ 000001b1bc8273c0] co located POCs unavailable
> [h264 @ 000001b1bc827840] co located POCs unavailable
> [h264 @ 000001b1bc827d00] co located POCs unavailable
> [h264 @ 000001b1bd3f54c0] co located POCs unavailable
> [graph 0 input from stream 0:0 @ 000001b1bc81b180] w:1280 h:720 pixfmt:yuvj420p tb:1/1200000 fr:15/1 sar:1/1
> [auto_scaler_0 @ 000001b1c0731300] w:iw h:ih flags:'bicubic' interl:0
> [format @ 000001b1bcd08f40] auto-inserting filter 'auto_scaler_0' between the filter 'Parsed_null_0' and the filter 'format'
> [swscaler @ 000001b1c0f3ac80] deprecated pixel format used, make sure you did set range correctly
> [auto_scaler_0 @ 000001b1c0731300] w:1280 h:720 fmt:yuvj420p sar:1/1 -> w:1280 h:720 fmt:yuv420p sar:1/1 flags:0x4
> [libx264 @ 000001b1bcbcb240] using SAR=1/1
> [libx264 @ 000001b1bcbcb240] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
> [libx264 @ 000001b1bcbcb240] profile High, level 3.1, 4:2:0, 8-bit
> [libx264 @ 000001b1bcbcb240] 264 - core 161 r3027 4121277 - H.264/MPEG-4 AVC codec - Copyleft 2003-2020 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=22 lookahead_threads=3 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=2 keyint=250 keyint_min=15 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
> Output #0, mp4, to '2021-08-1--16-07-40.mp4':
>   Metadata:
>     encoder         : Lavf58.45.100
>     Stream #0:0: Video: h264 (libx264), 1 reference frame (avc1 / 0x31637661), yuv420p(left), 1280x720 [SAR 1:1 DAR 16:9], q=-1--1, 15 fps, 15360 tbn, 15 tbc
>     Metadata:
>       encoder         : Lavc58.91.100 libx264
>     Side data:
>       cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
> No more output streams to write to, finishing.
> frame=    0 fps=0.0 q=0.0 Lsize=       0kB time=00:00:00.00 bitrate=N/A speed=   0x
> video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
> Input file #0 (pipe:):
>   Input stream #0:0 (video): 967 packets read (1355100 bytes); 0 frames decoded;
>   Total: 967 packets (1355100 bytes) demuxed
> Output file #0 (2021-08-1--16-07-40.mp4):
>   Output stream #0:0 (video): 0 frames encoded; 0 packets muxed (0 bytes);
>   Total: 0 packets (0 bytes) muxed
> [AVIOContext @ 000001b1bcbcbdc0] Statistics: 2 seeks, 3 writeouts
> [AVIOContext @ 000001b1bc7a7440] Statistics: 1355100 bytes read, 0

**Comment by dend** [comment]
Thanks for the output @rarrr - do you see this constantly, or only on certain runs? What OS are you running this on?

**Comment by rarrr** [comment]
Windows 10.  It started working yesterday with your latest push but this morning has failed again.
![image](https://user-images.githubusercontent.com/7687585/104111544-3dcbb880-5337-11eb-8021-54abfb43a9a2.png)
Noticing a lot of these:
![image](https://user-images.githubusercontent.com/7687585/104111549-4c19d480-5337-11eb-8cfa-ba77c637e6e9.png)

**Comment by dend** [comment]
Interesting. Thanks @rarrr - will look into this and add some extra debugging logic. I wonder what the unknown packet is. Expect to have a better build this evening.

**Comment by TomSelleck** [comment]
@dend Think I'm hitting the same issue, application appears to be running okay and outputting two files:

- 2021-12-1--09-14-58.mp4 - 1KB
- foggycam_2021-12-1--09-14-58.mp4 - 16KB

The first file doesn't seem to be playable, and the second is 10 seconds long but doesn't contain any video or audio:

![image](https://user-images.githubusercontent.com/2904599/104294990-d12bf780-54b7-11eb-9d81-d0e866cd5d58.png)

https://user-images.githubusercontent.com/2904599/104295067-ea34a880-54b7-11eb-92cd-30989c953320.mp4

https://user-images.githubusercontent.com/2904599/104295069-ea34a880-54b7-11eb-8c34-4145724bfe3f.mp4

**Comment by dend** [comment]
Cool - thank you @TomSelleck. I am looking into the issue this weekend.

**Comment by tarunmangla** [comment]
@dend I am getting the same error as @TomSelleck. The audio part of the mp4 file seems to be fine. I wonder if it is an issue with the encoding parameters? Thanks for your help!

**Comment by tarunmangla** [comment]
A little more digging in shows the following error on ffmpeg:  `decoding for stream 0 failed`.

**Comment by dend** [comment]
@tarunmangla @TomSelleck can you pull the latest source and build it? I've made some changes that also should show you the buffer length. Curious if you are able to share the final log from `foggycam` before it stops encoding in `ffmpeg`.
