### ISSUE TITLE
Thanks and a question/suggestion for live streaming rather than .MP4s

### ISSUE THREAD

**Issue by KayRJay** [dend/foggycam#59]
This is GREAT!  Thank you for both all the effort and the clear explanation of what you've done.   This is quite a tour de force!

As I understand your blog, you can capture a Nest stream and save it (without audio) to an .MP4 file.   I wonder if there is a way we could go somewhat further, and convert the Nest stream to ONVIF or some other "standard" (like "Generic URL Camera") on the fly.   

Instead, then, of creating a .MP4 file, I'm suggesting to have a server running on a computer (I use Macs) that could convert the steams of several Nest cams on my network (I have five) to a standard format that could be consumed by any of a wide range of hardware and software NVRs and home automation systems (I have ELAN).  Audio wouldn't be necessary, but of course would be helpful.

I hope this is something that interests you and that you would enjoy deploying your considerable geek skills to make happen!  Unfortunately, though I'm a well-used techie, I couldn't begin to implement this myself.

(By the way, check out [Camect](https://camect.com/camect-advanced-network-video-recorder/).... they seem to have figured out something similar to what you've done.  I'd bet they don't have Google's heip either!)

**Comment by dend** [comment]
Thanks for the feedback, @KayRJay - this is similar to what is being asked in #16. I have it on the radar, but no committed date yet, as I need to dig into the streaming protocol.
