### ISSUE TITLE
camera_config.json elements

### ISSUE THREAD

**Issue by busitj** [dend/foggycam#65]
Den, 

First thank you for your efforts.  

I'm having issues with obtaining the needed elements for the camera_config.json file.  Not being a programmer it took me some time to load Visual Studio and finally compile foggycam.  When I started editing the .json file and used the chrome developer console to find the necessary elements, I found I was out of my element.  I know there are sensitive parts so it is difficult to show each detail.  I have attached a picture of the basic console using Chrome and I'm hoping you can help.  I used your blog to try to find each element but although it gave me a iframe it was not what you had displayed.  

I have a nest account and my wife has paid through april, so wasn't sure if that interferes with coding used.  I tried searching what the user_agent was but couldn't understand whether this is merely the browser or a string such as: 

This is all I have in .json file. It shouldn't have any sensitive info, because I couldn't find it!: 
{
  "ffmpeg_path": "C:\ffmpeg-4.3\bin\ffmpeg.exe",
  "issue_token": "",
  "api_key": "",
  "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.72 Safari/537.36",
  "cookie": "",
  "nest_api_hostname": "https://home.nest.com",
  "camera_api_hostname": "https://webapi.camera.home.nest.com",
  "camera_auth_cookie": "website_ft"
}

Appreciate any help you can give.  Attached is the basic console pic from chrome, and a pic after I ran foggycam.exe with supported files shown...knowing it wouldn't work.  I accept this may be beyond my paygrade!  I was hoping a less costly and secure method to monitor outdoor video.  

Thanks, TJ

![New Bitmap Image1](https://user-images.githubusercontent.com/80177778/110222862-1870ac00-7e9b-11eb-8489-160ef80f8407.jpg)

![New Bitmap Image](https://user-images.githubusercontent.com/80177778/110222770-4d303380-7e9a-11eb-9620-5ee1c5372f2d.jpg)

**Comment by jacs90** [comment]
"ffmpeg_path": "C:\ffmpeg-4.3\bin\ffmpeg.exe",

needs to be

"ffmpeg_path": "C:\\\\ffmpeg-4.3\\\\bin\\\\ffmpeg.exe",

**Comment by cbjfan2009** [comment]
Mr. Delimarsky - thank you so much for  your efforts on this project.  Clearly a heavy investment of time and makes me feel humbly novice in your shadow!  I, too, am having issues getting the required config setup properly working.  Maybe a quick sample would show us what is needed?
I have put this into my config file.  Are there any glaring omissions or am I completely misinterpreting the readme directions on what URL and cookie value to include??  Tried to x-out any potential sensitive link information, even though the camera is outdoors and poses limited security concern.
**Note: my ffmpeg_path does have double "\\".** It just disappears after posting.

"ffmpeg_path": "C:\\Users\\prodsupervisor\\Downloads\\ffmpeg-2021-03-07-git-a7f841718f-full_build\\bin\\ffmpeg.exe",
"issue_token": "https://accounts.google.com/o/oauth2/iframerpc?action=issueToken&response_type=token%20id_token&login_hint=xxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxx_xxxxxxxxxxxxxxx-xxxxxxxxxxxxxx-xxxxxxxxxxxxxx&client_id=xxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com&origin=https%3A%2F%2Fhome.nest.com&scope=openid%20profile%20email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fnest-account&ss_domain=https%3A%2F%2Fhome.nest.com",
  "api_key": "",
  "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
  "cookie": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", **(74 character value I found using Firefox developer -- Network-- finding the call to iframerpc -- viewing response cookie set value:: if this is wrong, please indicate which cookie value should be placed here and simplest option to find said cookie value).**
  "nest_api_hostname": "https://home.nest.com",
  "camera_api_hostname": "https://webapi.camera.home.nest.com",
  "camera_auth_cookie": "website_ft"

Again, thank you so much for your efforts.  I've tried work-arounds using BlueStacks to run an Android webcam app (IP Cam Viewer Lite) that successfully views the shared-with-password stream plus adding in a screen-recording program to save the video.  Very inefficient and didn't really work consistently.

**Comment by jacs90** [comment]
> Mr. Delimarsky - thank you so much for your efforts on this project. Clearly a heavy investment of time and makes me feel humbly novice in your shadow! I, too, am having issues getting the required config setup properly working. Maybe a quick sample would show us what is needed?
> I have put this into my config file. Are there any glaring omissions or am I completely misinterpreting the readme directions on what URL and cookie value to include?? Tried to x-out any potential sensitive link information, even though the camera is outdoors and poses limited security concern.
> **Note: my ffmpeg_path does have double "\".** It just disappears after posting.
> 
> "ffmpeg_path": "C:\Users\prodsupervisor\Downloads\ffmpeg-2021-03-07-git-a7f841718f-full_build\bin\ffmpeg.exe",
> "issue_token": "https://accounts.google.com/o/oauth2/iframerpc?action=issueToken&response_type=token%20id_token&login_hint=xxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxx_xxxxxxxxxxxxxxx-xxxxxxxxxxxxxx-xxxxxxxxxxxxxx&client_id=xxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com&origin=https%3A%2F%2Fhome.nest.com&scope=openid%20profile%20email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fnest-account&ss_domain=https%3A%2F%2Fhome.nest.com",
> "api_key": "",
> "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
> "cookie": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", **(74 character value I found using Firefox developer -- Network-- finding the call to iframerpc -- viewing response cookie set value:: if this is wrong, please indicate which cookie value should be placed here and simplest option to find said cookie value).**
> "nest_api_hostname": "https://home.nest.com",
> "camera_api_hostname": "https://webapi.camera.home.nest.com",
> "camera_auth_cookie": "website_ft"
> 
> Again, thank you so much for your efforts. I've tried work-arounds using BlueStacks to run an Android webcam app (IP Cam Viewer Lite) that successfully views the shared-with-password stream plus adding in a screen-recording program to save the video. Very inefficient and didn't really work consistently.

Looks ok to me what you have shown. The cookie is from the last iframe. I used the instructions in 
https://www.npmjs.com/package/homebridge-nest 
"Using a Google Account" section

**Comment by cbjfan2009** [comment]
> 
> Looks ok to me what you have shown. The cookie is from the last iframe. I used the instructions in
> https://www.npmjs.com/package/homebridge-nest
> "Using a Google Account" section

Thank you so much jacs90.  That link you posted ('instructions') was exactly what I needed.  I think I had copied the cookie value out of the response header when, as the instructions suggest, I needed to use the value out of the request header.
